angular.module("frontpress.components.list-posts", 
				["frontpress.filters", 
				"frontpress.components.slugs-map", 
				"frontpress.apis.posts", 
				"frontpress.apis.media", 
				"frontpress.components.api-manager", 
				"frontpress.components.post-date",
				"frontpress.components.featured-image",
				"frontpress.components.frontpress-provider"]);
